service:
  name: specialcaring-serverless

# Add the serverless-webpack plugin
plugins:
  - serverless-webpack
  - serverless-offline
provider:
  name: aws
  runtime: nodejs8.10

custom:
  webpack:
    webpackConfig: 'webpack.config.js'   # Name of webpack configuration file
    includeModules: true
    packager: 'yarn'   # Packager that will be used to package your external modules

functions:
  graphql:
    handler: handler.server
    events:
    - http:
        path: /
        method: post
        cors: true
  playground:
    handler: handler.playground
    events:
    - http:
        path: /
        method: get
        cors: true